version: 2
general:
  branches:
    ignore:
      - gh-pages
jobs:
  dotnet1:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:1.1-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - run: cat /etc/os-release
      - run: apt-get update
      - run: apt-get install -y dnsutils
      - run: dig cloudflare-dns.com. A +dnssec
      - checkout
      - run: dotnet restore
      - run: dotnet build ./src/Udns.csproj -c Release --framework netstandard14 
      - run: dotnet test ./test/UdnsTests.csproj -c Release --framework netcoreapp1.1

  dotnet2:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - run: cat /etc/os-release
      - run: apt-get update
      - run: apt-get install -y dnsutils
      - run: dig cloudflare-dns.com. A +dnssec
      - checkout
      - run: dotnet restore
      - run: dotnet build ./src/Udns.csproj -c Release --framework netstandard2 
      - run: dotnet test ./test/UdnsTests.csproj -c Release --framework netcoreapp2
workflows:
  version: 2
  build-all:
    jobs:
      - dotnet2
      - dotnet1
